/* Offline cache for the installable tools. Generated by build/build_site.py
   from the pieces marked as installing to a phone; do not edit by hand, the
   next build overwrites it. Version changes whenever a cached file changes,
   which is what retires the previous cache. */
const VERSION = "3ba4e48db3ff";
const CACHE   = "site-" + VERSION;
const FILES   = [
  "daily-learning-cockpit-192.png",
  "daily-learning-cockpit-512.png",
  "daily-learning-cockpit.html",
  "daily-learning-cockpit.webmanifest",
  "law-arena-192.png",
  "law-arena-512.png",
  "law-arena.html",
  "law-arena.webmanifest",
  "skill-forge-192.png",
  "skill-forge-512.png",
  "skill-forge.html",
  "skill-forge.webmanifest"
];

self.addEventListener("install", e => {
  e.waitUntil(
    caches.open(CACHE)
      // addAll is all-or-nothing, so one missing file would leave the tools
      // with no cache at all. Each file is added on its own and a failure is
      // survivable: the rest still work offline.
      .then(c => Promise.all(FILES.map(f => c.add(f).catch(() => null))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  // Network first, so a published change is picked up as soon as there is a
  // connection; the cache is the fallback that makes the offline claim true.
  e.respondWith(
    fetch(req)
      .then(res => {
        if (res && res.ok && res.type === "basic") {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
        }
        return res;
      })
      .catch(() => caches.match(req).then(hit => hit || caches.match("index.html")))
  );
});
